github:
  description: "Apache Incubator Website"
  homepage: "https://incubator.apache.org/"
  labels:
    - incubator
    - website
    - jbake

notifications:
  commits:      cvs@incubator.apache.org
  pullrequests: cvs@incubator.apache.org
