//
//  Licensed to the Apache Software Foundation (ASF) under one or more
//  contributor license agreements.  See the NOTICE file distributed with
//  this work for additional information regarding copyright ownership.
//  The ASF licenses this file to You under the Apache License, Version 2.0
//  (the "License"); you may not use this file except in compliance with
//  the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
:imagesdir: ../images/

== Creating Presentation with Apache Training

Currently the setup uses https://asciidoctor.org/[Asciidoctor] to write content and builds the presentation using https://maven.apache.org/[Apache Maven] and https://revealjs.com/#/[Reveal.JS].

We have prepared everything that it should be pretty simple to get started with creating a new presentation.

Requirements:

- Java 8 or newer
- Maven 3.3 or newer

Until we have released the tooling, you will need to build it locally first or the archetype plugin will fail to run.
Please read the following chapter on how to do this.

In order to create an empty presentation to start with, please execute the following command:

    mvn archetype:generate -DarchetypeGroupId=org.apache.training -DarchetypeArtifactId=content-archetype -DarchetypeVersion=1.0.0-SNAPSHOT

After choosing `groupId`, `artifactId`, `version` and `package` there should be a new directory that matches the `artifactId` that you selected.

Change into this directory and run the following command to build the presentation:

    mvn package

After that, there should be a directory `target/generated-slides`.

If you open the `index.html` in that directory your presentation should open in the browser.

== Building the Apache Training Tooling

Additional requirements:

- Git

In order to build Apache Training Tooling, please checkout the git repo from:

    git clone https://gitbox.apache.org/repos/asf/incubator-training.git
    cd incubator-training
    mvn install

Then execute the following command:

    mvn clean install